name: "Build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.board }}
    strategy:
      fail-fast: false
      matrix:
        board: [weact_studio_rp2040_16mb]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fix submodule URLs and update
        run: |
          sed -i 's|url = \.\./|url = https://github.com/lizzzhh/|g' .gitmodules
          git submodule sync
          git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
      - name: Clone and build pico-sdk
        run: |
          git clone https://github.com/raspberrypi/pico-sdk
          cd pico-sdk
          git checkout tags/2.1.1
          git submodule update --init
          cd ..
      - name: Build firmware
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
        run: |
          mkdir -p build_ci
          cd build_ci
          cmake .. -DPICO_BOARD=waveshare_rp2350_zero
          make -j$(nproc)
